/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Employee.Employee;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import UI.MainJFrame;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class CustomerJFrame extends javax.swing.JFrame {

    DefaultTableModel viewTableModel;
    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    public CustomerJFrame() {
        initComponents();
    }

    public CustomerJFrame(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnRentBook = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnRentHistory = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        btnRentMag = new javax.swing.JButton();
        btnRentMagazine = new javax.swing.JButton();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlJPanel.setBackground(new java.awt.Color(153, 255, 255));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRentBook.setText("Rent Book");
        btnRentBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentBookActionPerformed(evt);
            }
        });
        controlJPanel.add(btnRentBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 20));

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        controlJPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 110, 20));

        btnRentHistory.setText("Check Rent History");
        btnRentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentHistoryActionPerformed(evt);
            }
        });
        controlJPanel.add(btnRentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, 20));

        jLabelWelcome.setText("Username");
        controlJPanel.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabelUser.setText("name");
        controlJPanel.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 42, -1));

        btnRentMag.setText("Rent Magazine");
        btnRentMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentMagActionPerformed(evt);
            }
        });
        controlJPanel.add(btnRentMag, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, 20));

        btnRentMagazine.setText("Check Magazine History");
        btnRentMagazine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentMagazineActionPerformed(evt);
            }
        });
        controlJPanel.add(btnRentMagazine, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 20));

        jSplitPane1.setLeftComponent(controlJPanel);

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanel.setLayout(displayJPanelLayout);
        displayJPanelLayout.setHorizontalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        displayJPanelLayout.setVerticalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(displayJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentBookActionPerformed
        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new RentBookJPanel(this.applicationsystem,this.branch, this.useraccount));
    }//GEN-LAST:event_btnRentBookActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.applicationsystem,this.branch, this.useraccount);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnRentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentHistoryActionPerformed
        // TODO add your handling code here:
     jSplitPane1.setRightComponent(new ViewBookJPanel(this.applicationsystem,this.branch, this.useraccount));

    }//GEN-LAST:event_btnRentHistoryActionPerformed

    private void btnRentMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentMagActionPerformed
        // TODO add your handling code here:
     jSplitPane1.setRightComponent(new RentMagazineJPanel(this.applicationsystem,this.branch, this.useraccount));

    }//GEN-LAST:event_btnRentMagActionPerformed

    private void btnRentMagazineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentMagazineActionPerformed
        // TODO add your handling code here:
     jSplitPane1.setRightComponent(new ViewMagazineJPanel(this.applicationsystem,this.branch, this.useraccount));

    }//GEN-LAST:event_btnRentMagazineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerJFrame().setVisible(true);
            }
        });
    }
    
    public void displayLocation()
    {
       
        jLabelUser.setText(useraccount.getUsername());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRentBook;
    private javax.swing.JButton btnRentHistory;
    private javax.swing.JButton btnRentMag;
    private javax.swing.JButton btnRentMagazine;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
