/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.Customer;

import Customer.Customer;
import Employee.Employee;
import Employee.EmployeeDirectory;
import Library.Library;
import Material.Book;
import Material.BookDirectory;
import Material.General;
import Material.Magazine;
import Rental.Rent;
import Role.LibrarianRole;
import Role.Role;
import Role.SystemAdminRole;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import System.UserAccountDirectory;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ViewMagazineJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;

    
    public ViewMagazineJPanel() {
        initComponents();

    }

    public ViewMagazineJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) tableBookTable.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayLocationDp();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboLocationBox = new javax.swing.JComboBox<>();
        btnReturnBook = new javax.swing.JButton();
        btnViewLocation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("RENT HISTORY - MAGAZINE");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, -1));

        jLabel2.setText("Select Location");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 20));

        comboLocationBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(comboLocationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 30));

        btnReturnBook.setText("Return Book");
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });
        add(btnReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 110, 20));

        btnViewLocation.setText("VIEW");
        btnViewLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocationActionPerformed(evt);
            }
        });
        add(btnViewLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, 20));

        tableBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Issue type", "Date", "Available", "Rent Price", "Rent Duration", "Serial Number", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBookTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 770, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        // TODO add your handling code here:
    int selectedRow = tableBookTable.getSelectedRow();
             if(selectedRow >= 0 ){
            String selectSerialNumber = tableBookTable.getValueAt(selectedRow, 9).toString();
            Library lib = this.branch.getLib();
             ArrayList<Magazine> magList = lib.getGeneralList().getMagazineCollection();

              for(int i =0;i< magList.size();i++ ){
                  long serialNumber = magList.get(i).getRt().getSerialNumber();
                  
               if( serialNumber == Long.valueOf(selectSerialNumber) )
               {
                   Magazine bk= magList.get(i);
                   bk.setIsAvailableFlag(true);
                  Rent rt = bk.getRt();
                  rt.setBookRequested("RETURNED");
                  bk.setRt(rt);
                  this.applicationsystem.UpdateMagazineToBranch(magList.get(i).getLocation(),bk);
                  this.applicationsystem.getCustomerList().updateRentStatus(this.useraccount.getAccountId(), rt);
                  break;
               }
              }
               JOptionPane.showMessageDialog(null, "Accepted Request");
              
        }
        
        
        
    }//GEN-LAST:event_btnReturnBookActionPerformed

    private void btnViewLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocationActionPerformed
        // TODO add your handling code here:
            String location = (String) comboLocationBox.getSelectedItem();
        displayBookTableDetails(location);
    }//GEN-LAST:event_btnViewLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnViewLocation;
    private javax.swing.JComboBox<String> comboLocationBox;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBookTable;
    // End of variables declaration//GEN-END:variables



    
       private void displayLocationDp() {
            comboLocationBox.removeAllItems();
         ArrayList<String> br = this.applicationsystem.getBranchName();
        for (int i = 0; i < br.size(); i++)
        {
            comboLocationBox.addItem(br.get(i));
        }
        
    }

    private void displayBookTableDetails(String location) {
        ArrayList<Customer> cust = this.applicationsystem.getCustomerList().getCustomerlist();
        ArrayList<String> rentArray = new ArrayList<String>();
      for(int i =0; i< cust.size();i++){
          if(cust.get(i).getCustomerId().equals(useraccount.getAccountId()))
          {
            ArrayList<Rent> rt = cust.get(i).getRentlist();
          for(int j=0;j<rt.size();j++){
              rentArray.add(rt.get(j).getRentId());
          }  
          }
          
      }
      
      Library lib = this.branch.getLib();
        ArrayList<Magazine> magList = lib.getGeneralList().getMagazineCollection();
        
             for(int i =0;i< magList.size();i++ ){
               
               
               if(magList.get(i).getLocation().equals(location))
               {
                   for(int j=0;j<rentArray.size();j++){
                   
                   if(rentArray.get(j) == magList.get(i).getRt().getRentId() )
                   {
                       Object row[] = new Object[12];
                     row[0] = magList.get(i).getMaterialName();
                  
                     row[1] = magList.get(i).getIssueType();
                     row[2] = String.valueOf(magList.get(i).getRegisteredDate());
                     row[3] = magList.get(i).getRt().getRentPrice();
                     row[4] = magList.get(i).getRt().getRentDuration();
                     row[5] = magList.get(i).getRt().getSerialNumber();
                     row[6] = magList.get(i).getRt().getBookRequested();
                     viewTableModel.addRow(row);
                   }
                   
                   }
               }
             }
    }
    
}
      
      
      
      
      
      
      
              
        
        
        
   
        

    
    
    
 
     


