/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.SystemAdminPanel;

import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class CreateBranchJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    ArrayList<Integer> buildingNumber;

    public CreateBranchJPanel() {
        initComponents();

    }

    CreateBranchJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
         this.viewTableModel = (DefaultTableModel) tblBranch.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        this.buildingNumber = new ArrayList<Integer>();
        displayBranch();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        branchTextField = new javax.swing.JTextField();
        btnCreateBranch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBranch = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        libTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buildingNoTextField = new javax.swing.JTextField();
        btnDeleteBranch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Create Branch");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 100, 20));

        branchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                branchTextFieldFocusLost(evt);
            }
        });
        branchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchTextFieldActionPerformed(evt);
            }
        });
        add(branchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, 30));

        btnCreateBranch.setText("Add");
        btnCreateBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBranchActionPerformed(evt);
            }
        });
        add(btnCreateBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        tblBranch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Library", "Building No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBranch);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 490, 190));

        jLabel2.setText("Library Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, 20));

        libTextField.setEnabled(false);
        add(libTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 30));

        jLabel3.setText("Building No");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 60, 20));
        add(buildingNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 30));

        btnDeleteBranch.setText("Delete");
        btnDeleteBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBranchActionPerformed(evt);
            }
        });
        add(btnDeleteBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, -1, -1));

        jLabel4.setText("Branch Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBranchActionPerformed
        // TODO add your handling code here:
        String branchName = branchTextField.getText();
        String libraryName = branchName + " Library";
        int buildingNum = Integer.valueOf(buildingNoTextField.getText());
        Boolean branchExist = this.applicationsystem.branchAlreadyUsed(branchName);
        this.buildingNumber.add(buildingNum);
        
        if(!branchExist){
             this.applicationsystem.storeBranchName(branchName);
             JOptionPane.showMessageDialog(null, "Branch Added Successfully");
        }
        else {
             JOptionPane.showMessageDialog(null, "Add New Branch - Already exists");   
        }
        
      
        displayBranch();
    }//GEN-LAST:event_btnCreateBranchActionPerformed

    private void branchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_branchTextFieldFocusLost
        // TODO add your handling code here:
        String branchName = branchTextField.getText();
        libTextField.setText(branchName + " Library");
    }//GEN-LAST:event_branchTextFieldFocusLost

    private void btnDeleteBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBranchActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBranch.getSelectedRow();
        if(selectedRow >= 0 ){
        String selectBranchName = tblBranch.getValueAt(selectedRow, 0).toString();
        System.out.println(" selectBranch "+selectBranchName);
        this.applicationsystem.removeBranch(selectBranchName);
         JOptionPane.showMessageDialog(null, "Branch deleted");  
         displayBranch();
        }
        else {
             JOptionPane.showMessageDialog(null, "Select a branch");  
        }
 
    }//GEN-LAST:event_btnDeleteBranchActionPerformed

    private void branchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branchTextField;
    private javax.swing.JButton btnCreateBranch;
    private javax.swing.JButton btnDeleteBranch;
    private javax.swing.JTextField buildingNoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libTextField;
    private javax.swing.JTable tblBranch;
    // End of variables declaration//GEN-END:variables

    private void displayBranch() {
        ArrayList<String> br = this.applicationsystem.getBranchName();
        
        if(br.size() > 0){
            viewTableModel.setRowCount(0);
        for (int i = 0; i < br.size(); i++)
         {  

            Object row[]= new Object[4];
            row[0] = br.get(i);
            row[1] = br.get(i) + " Library";
            row[2] = buildingNumber.get(i);
            viewTableModel.addRow(row);
    }
        }
    }

}
