/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.SystemAdminPanel;

import Customer.Customer;
import Customer.CustomerDirectory;
import Employee.Employee;
import Employee.EmployeeDirectory;
import Role.CustomerRole;
import Role.Role;
import Role.SystemAdminRole;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import System.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class CustomerJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    /** Creates new form CreateBranchJPanel */

    
    public CustomerJPanel() {
        initComponents();
    }

    public CustomerJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) customerTable.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayCustomer();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addCustomerBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customerNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        customerAgeTextField = new javax.swing.JTextField();
        custUsernameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        customerPasswordTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Customer Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 90, 20));

        addCustomerBtn.setText("Add");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });
        add(addCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, 20));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 480, 250));

        customerNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameTextFieldFocusLost(evt);
            }
        });
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });
        add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 30));

        jLabel3.setText("Customer Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 20));

        customerAgeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerAgeTextFieldFocusLost(evt);
            }
        });
        add(customerAgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        custUsernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custUsernameTextFieldFocusLost(evt);
            }
        });
        add(custUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 30));

        jLabel7.setText("UserName");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 20));

        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 60, 30));

        customerPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerPasswordTextFieldFocusLost(evt);
            }
        });
        add(customerPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 30));

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Add Customer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed
        // TODO add your handling code here:

          String custName = customerNameTextField.getText();
          String custAge = customerAgeTextField.getText();
          String userName = custUsernameTextField.getText();
          String passWord = customerPasswordTextField.getText();
            
        UserAccountDirectory ua = this.applicationsystem.getTopLevelUserAccountDirectory();
        if(ua.accountExists(userName)) {
            JOptionPane.showMessageDialog(null, "Sorry  credentials are taken");
            
        }
        else {
            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().createUserAccount(userName, passWord , new CustomerRole(),"ALL");
            this.applicationsystem.getCustomerList().addCustomer(custName,Integer.valueOf(custAge),user.getAccountId());
            JOptionPane.showMessageDialog(null, "Customer has been added");
            displayCustomer();
        }
          
          
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void customerNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldFocusLost

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void customerAgeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerAgeTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAgeTextFieldFocusLost

    private void custUsernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custUsernameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_custUsernameTextFieldFocusLost

    private void customerPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerPasswordTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customerPasswordTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField custUsernameTextField;
    private javax.swing.JTextField customerAgeTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField customerPasswordTextField;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void displayCustomer() {
        ArrayList<Customer> cust = this.applicationsystem.getCustomerList().getCustomerlist();

        viewTableModel.setRowCount(0);
        
        for(int i=0;i<cust.size();i++){
             Object row[] = new Object[6];
             UserAccount u = this.applicationsystem.getTopLevelUserAccountDirectory().findbyId(cust.get(i).getCustomerId());
              row[0] = cust.get(i).getCustomerName();
              row[1] = cust.get(i).getCustomerAge();
              row[2] = u.getUsername();
              row[3] = u.getPassword();
              viewTableModel.addRow(row);
        }

                        
    }

}
