/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.SystemAdminPanel;

import Employee.Employee;
import Employee.EmployeeDirectory;
import Library.Library;
import Material.BookDirectory;
import Role.LibrarianRole;
import Role.Role;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import System.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ManageLibrarian extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    /** Creates new form CreateBranchJPanel */

    
    public ManageLibrarian() {
        initComponents();

    }

    ManageLibrarian(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) librarianTableContent.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        
        displayLibraryDp();
        displayLibrarian();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        experienceTextField = new javax.swing.JTextField();
        btnLibSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        librarianTableContent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxLibrary = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        usrNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 20));

        experienceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                experienceTextFieldFocusLost(evt);
            }
        });
        add(experienceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 30));

        btnLibSubmit.setText("Add");
        btnLibSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibSubmitActionPerformed(evt);
            }
        });
        add(btnLibSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 70, -1));

        librarianTableContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Library", "Branch Name", "Username", "Password", "Experience", "Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(librarianTableContent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 660, 190));

        jLabel2.setText("Experience");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, 40));

        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 70, 20));

        comboBoxLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLibraryActionPerformed(evt);
            }
        });
        add(comboBoxLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 120, 30));

        jLabel4.setText("Assign Branch");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 20));

        ageTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageTextFieldFocusLost(evt);
            }
        });
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        usrNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrNameTextFieldFocusLost(evt);
            }
        });
        add(usrNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, 30));

        jLabel7.setText("Username");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, 20));

        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 60, 20));

        passTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFieldFocusLost(evt);
            }
        });
        add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, 30));

        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("Add Librarian");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibSubmitActionPerformed
 
        UserAccountDirectory ua = this.applicationsystem.getTopLevelUserAccountDirectory();
        if(ua.accountExists(usrNameTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Already Exists");
            
        }
        else {
          String libName = nameTextField.getText();
          String libAge = ageTextField.getText();
          String libraryName = (String) comboBoxLibrary.getSelectedItem();
          String experience = experienceTextField.getText();
          String userName = usrNameTextField.getText();
          String passWord = passTextField.getText();
            Boolean checkBranchAssigned = this.applicationsystem.branchAlreadyAssigned((String) comboBoxLibrary.getSelectedItem(),"librarian");
            if(!checkBranchAssigned){
            String accessTo = (String) comboBoxLibrary.getSelectedItem();
            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().createUserAccount(userName, passWord , new LibrarianRole(),accessTo);
            Library lib = this.branch.getLib();
            EmployeeDirectory emp = lib.getEmployeelist();
            Employee e = new Employee();
            e.setPersonId(user.getAccountId());
            e.setName(libName);
            e.setAge(Integer.valueOf(libAge));
            e.setExperience(Integer.valueOf(experience));
            e.setDesignation("librarian");
            e.setLibraryName(libraryName);
            emp.getEmployeelist().add(e);
            lib.setEmployeelist(emp);
            lib.setLibraryName(libraryName);
           
            this.applicationsystem.AddEmpToBranch((String) comboBoxLibrary.getSelectedItem(), lib);

            JOptionPane.showMessageDialog(null, "Employee added");
            
            }
            else {
                JOptionPane.showMessageDialog(null, "Select other Branch");
            }
            
            }
            displayLibrarian();
        
         
    }//GEN-LAST:event_btnLibSubmitActionPerformed

    private void experienceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_experienceTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_experienceTextFieldFocusLost

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void comboBoxLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxLibraryActionPerformed

    private void ageTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldFocusLost

    private void usrNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usrNameTextFieldFocusLost

    private void passTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextFieldFocusLost

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton btnLibSubmit;
    private javax.swing.JComboBox<String> comboBoxLibrary;
    private javax.swing.JTextField experienceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable librarianTableContent;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField passTextField;
    private javax.swing.JTextField usrNameTextField;
    // End of variables declaration//GEN-END:variables

    private void displayLibrarian() {
        
        ArrayList<Branch> x = this.applicationsystem.getBranches();
         ArrayList<String> rm = this.applicationsystem.getBranchName();
        System.out.println("Size of branches of librarian:  "+ x.size());
        viewTableModel.setRowCount(0);
        
        for(int i=0 ; i < x.size(); i++ )
        {
            for(int j=0;j< rm.size();j++ ){
                String designation = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getDesignation();
            if(rm.get(j).equals(x.get(i).getName()) && designation.equals("librarian"))
            {
            Object row[] = new Object[8];
             String userName = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getPersonId();
             UserAccount u = this.applicationsystem.getTopLevelUserAccountDirectory().findbyId(userName);
               row[0] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getName();
               row[1] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getAge();
               row[2] = x.get(i).getName() + " Library";
               row[3] = x.get(i).getName();
               row[4] = u.getUsername();
               row[5] = u.getPassword();
               row[6] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getExperience();
               row[7] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getDesignation();
               viewTableModel.addRow(row);
        }
            }

            }
    }
                         
    
    
      private void displayLibraryDp() {
         comboBoxLibrary.removeAllItems();
         ArrayList<String> br = this.applicationsystem.getBranchName();
        for (int i = 0; i < br.size(); i++)
        {
            comboBoxLibrary.addItem(br.get(i));
        }
    }

}
