/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.SystemAdminPanel;

import Employee.Employee;
import Employee.EmployeeDirectory;
import Library.Library;
import Role.BranchManagerRole;
import Role.LibrarianRole;
import Role.Role;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import System.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class ManageBranchMJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;

    
    public ManageBranchMJPanel() {
        initComponents();

    }

    ManageBranchMJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) tableBM.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayRemoveBranch();
        displayLibraryDp();
        displayBranchManager();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        brmgrExpTextField = new javax.swing.JTextField();
        addBM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBM = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        brmgrNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxLib = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        brmgrAgeTextField = new javax.swing.JTextField();
        usrNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 20));

        brmgrExpTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                brmgrExpTextFieldFocusLost(evt);
            }
        });
        brmgrExpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brmgrExpTextFieldActionPerformed(evt);
            }
        });
        add(brmgrExpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 30));

        addBM.setText("Add");
        addBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBMActionPerformed(evt);
            }
        });
        add(addBM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 70, 20));

        tableBM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Library", "Branch Name", "Username", "Password", "Experience", "Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBM);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 750, 190));

        jLabel2.setText("Experience");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, 30));

        brmgrNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                brmgrNameTextFieldFocusLost(evt);
            }
        });
        brmgrNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brmgrNameTextFieldActionPerformed(evt);
            }
        });
        add(brmgrNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 30));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 40, 20));

        comboBoxLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLibActionPerformed(evt);
            }
        });
        add(comboBoxLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 30));

        jLabel4.setText("Assign Branch");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 20));

        brmgrAgeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                brmgrAgeTextFieldFocusLost(evt);
            }
        });
        add(brmgrAgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, 30));

        usrNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrNameTextFieldFocusLost(evt);
            }
        });
        add(usrNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 110, 30));

        jLabel7.setText("UserName");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 60, 20));

        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 60, 20));

        passTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFieldFocusLost(evt);
            }
        });
        add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 110, 30));

        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Add Branch Manager");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBMActionPerformed

            
        UserAccountDirectory ua = this.applicationsystem.getTopLevelUserAccountDirectory();
        if(ua.accountExists(usrNameTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Already exists");
            
        }
        else {
          String libName = brmgrNameTextField.getText();
          String libAge = brmgrAgeTextField.getText();
          String libraryName = (String) comboBoxLib.getSelectedItem() + " Library";
          String experience = brmgrExpTextField.getText();
          String userName = usrNameTextField.getText();
          String passWord = passTextField.getText();
            Boolean checkBranchAssigned = this.applicationsystem.branchAlreadyAssigned((String) comboBoxLib.getSelectedItem(),"branch manager");
            if(!checkBranchAssigned)
            {
                String accessTo = (String) comboBoxLib.getSelectedItem();
            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().createUserAccount(userName, passWord , new BranchManagerRole(),accessTo);
            Library lib = this.branch.getLib();
            EmployeeDirectory emp = lib.getEmployeelist();
            Employee e = new Employee();
            e.setPersonId(user.getAccountId());
            e.setName(libName);
            e.setAge(Integer.valueOf(libAge));
            e.setExperience(Integer.valueOf(experience));
            e.setDesignation("branch manager");
            emp.getEmployeelist().add(e);
            lib.setEmployeelist(emp);
            lib.setLibraryName(libraryName);
            
            this.applicationsystem.AddEmpToBranch((String) comboBoxLib.getSelectedItem(), lib);
            
            
            JOptionPane.showMessageDialog(null, "Employee added");
            }
            else {
                JOptionPane.showMessageDialog(null, "Select other branch");
            }
            
  
            }
            displayBranchManager();
          
    }//GEN-LAST:event_addBMActionPerformed

    private void brmgrExpTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brmgrExpTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_brmgrExpTextFieldFocusLost

    private void brmgrNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brmgrNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_brmgrNameTextFieldFocusLost

    private void brmgrNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brmgrNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brmgrNameTextFieldActionPerformed

    private void comboBoxLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxLibActionPerformed

    private void brmgrAgeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_brmgrAgeTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_brmgrAgeTextFieldFocusLost

    private void usrNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_usrNameTextFieldFocusLost

    private void passTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextFieldFocusLost

    private void brmgrExpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brmgrExpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brmgrExpTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBM;
    private javax.swing.JTextField brmgrAgeTextField;
    private javax.swing.JTextField brmgrExpTextField;
    private javax.swing.JTextField brmgrNameTextField;
    private javax.swing.JComboBox<String> comboBoxLib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passTextField;
    private javax.swing.JTable tableBM;
    private javax.swing.JTextField usrNameTextField;
    // End of variables declaration//GEN-END:variables

    private void displayLibraryDp() {
         comboBoxLib.removeAllItems();
         ArrayList<String> br = this.applicationsystem.getBranchName();
        for (int i = 0; i < br.size(); i++)
        {
            comboBoxLib.addItem(br.get(i));
        }
    }
    
    private void displayBranchManager() {

        ArrayList<Branch> x = this.applicationsystem.getBranches();
         ArrayList<String> rm = this.applicationsystem.getBranchName();
        
        System.out.println("Size of branches of librarian:  "+ x.size());
        viewTableModel.setRowCount(0);
       
        for(int i=0 ; i < x.size(); i++ )
        {
         for(int j=0;j< rm.size();j++ ){
             String designation = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getDesignation();
            if(rm.get(j).equals(x.get(i).getName()) && designation.equals("branch manager") )
            {
                Object row[] = new Object[8];
             String userName = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getPersonId();
             UserAccount u = this.applicationsystem.getTopLevelUserAccountDirectory().findbyId(userName);
               row[0] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getName();
               row[1] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getAge();
               row[2] = x.get(i).getName() + " Library";
               row[3] = x.get(i).getName();
               row[4] = u.getUsername();
              row[5] = u.getPassword();
              row[6] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getExperience();
               row[7] = x.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getDesignation();
             viewTableModel.addRow(row);
            }
        }
            
            
        }
    }

    private void displayRemoveBranch() {
       
       
    }

}
