/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BranchManager;

import Employee.Employee;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import UI.MainJFrame;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class BranchManagerJFrame extends javax.swing.JFrame {

    DefaultTableModel viewTableModel;
    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    public BranchManagerJFrame() {
        initComponents();
    }

    public BranchManagerJFrame(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        btnMaterialCollection = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        btnRentalRequest = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlJPanel.setBackground(new java.awt.Color(153, 255, 204));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaterialCollection.setText("View Material Collection");
        btnMaterialCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialCollectionActionPerformed(evt);
            }
        });
        controlJPanel.add(btnMaterialCollection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 20));

        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        controlJPanel.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, 20));

        jLabel1.setText("Location");
        controlJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 79, -1));

        locationTextField.setEnabled(false);
        locationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextFieldActionPerformed(evt);
            }
        });
        controlJPanel.add(locationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 95, -1));

        btnRentalRequest.setText("View Rental Request");
        btnRentalRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalRequestActionPerformed(evt);
            }
        });
        controlJPanel.add(btnRentalRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 20));

        jLabelWelcome.setText("Username");
        controlJPanel.add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabelUser.setText("name");
        controlJPanel.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 42, -1));

        jSplitPane1.setLeftComponent(controlJPanel);

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanel.setLayout(displayJPanelLayout);
        displayJPanelLayout.setHorizontalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        displayJPanelLayout.setVerticalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(displayJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaterialCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialCollectionActionPerformed
        // TODO add your handling code here:
        
        jSplitPane1.setRightComponent(new ViewMaterialJPanel(this.applicationsystem,this.branch, this.useraccount));
    }//GEN-LAST:event_btnMaterialCollectionActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.applicationsystem,this.branch, this.useraccount);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed

    private void btnRentalRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalRequestActionPerformed
        // TODO add your handling code here:
                jSplitPane1.setRightComponent(new ViewRentalJPanel(this.applicationsystem,this.branch, this.useraccount));

    }//GEN-LAST:event_btnRentalRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchManagerJFrame().setVisible(true);
            }
        });
    }
    
//    public void displayLocation()
//    {
//        jLabelUser.setText(useraccount.getAccountId());
//    }
//    
    public void displayLocation()
    {
        jLabelUser.setText(useraccount.getUsername());
        
        locationTextField.setText(useraccount.getAccessTo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMaterialCollection;
    private javax.swing.JButton btnRentalRequest;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField locationTextField;
    // End of variables declaration//GEN-END:variables
}