/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Role.Role;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 91730
 */
public class MainJFrame extends javax.swing.JFrame {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    public MainJFrame() {
        initComponents();
        this.applicationsystem = ApplicationSystem.getInstance();
        this.branch = new Branch();
        this.useraccount = new UserAccount();
        populateDropdown();
    }
    
    public MainJFrame(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        populateDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUserName1 = new javax.swing.JTextField();
        comboBoxRole = new javax.swing.JComboBox<>();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+4));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Library Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 248, 39));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 97, 30));
        jPanel1.add(txtUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 97, 30));

        jPanel1.add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 20));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 87, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        Boolean foundUser = false;
        if(this.applicationsystem.getTopLevelUserAccountDirectory().authenticateUser(txtUserName1.getText(), txtPassword.getText()) != null) {
            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().authenticateUser(txtUserName1.getText(), txtPassword.getText());
               Branch branch = null;
                Role fetchRole = user.getRole();
                System.out.println("The Role of this user is " +fetchRole.toString());
                
                if(fetchRole.toString().contains("SystemAdmin")  ){
                     branch = new Branch();
                   
                    
                }
                else if(fetchRole.toString().contains("Librarian") || fetchRole.toString().contains("BranchManager")){

                    ArrayList<Branch> br = this.applicationsystem.getBranches();
                    for(int i =0 ; i< br.size();i++)
                    {
                        if(br.get(i).getName().equals(user.getAccessTo()))
                        {
                             System.out.println("USER ACCESS "+ user.getAccessTo());
                             branch = br.get(i);
                              break;
                        }
                           
                       
                    }
                    
                    System.out.println("BRANCH IN "+branch.getName());
                }
                else if(fetchRole.toString().contains("Customer") ){
                    System.out.println("Entered the value of Customer");
                    branch = this.branch;
                }
                
            foundUser = true;
            user.getRole().createWorkArea(this.applicationsystem, branch, user);
            
            this.setVisible(false);
        } else {
            for(Branch branch: this.applicationsystem.getBranches()) {
                if(branch.getBranchuseraccountDirectory().authenticateUser(txtUserName1.getText(), txtPassword.getText()) != null) {
                    UserAccount branchUser = branch.getBranchuseraccountDirectory().authenticateUser(txtUserName1.getText(), txtPassword.getText());
                    foundUser = true;
                    branchUser.getRole().createWorkArea(this.applicationsystem,this.branch, this.useraccount);
                    this.setVisible(false);
                }
            }
        }

        if(!foundUser) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
        }
    }//GEN-LAST:event_loginBtnActionPerformed
       private void populateDropdown() {
          comboBoxRole.removeAllItems();
        
        for(String rolename: Role.getAllRoles()) {
            comboBoxRole.addItem(rolename);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName1;
    // End of variables declaration//GEN-END:variables

    
}
