/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.Librarian;

import Employee.Employee;
import Employee.EmployeeDirectory;
import Library.Library;
import Material.Book;
import Material.BookDirectory;
import Rental.Rent;
import Role.LibrarianRole;
import Role.Role;
import Role.SystemAdminRole;
import System.ApplicationSystem;
import System.Branch;
import System.UserAccount;
import System.UserAccountDirectory;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91730
 */
public class AddBookJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    /** Creates new form CreateBranchJPanel */

    
    public AddBookJPanel() {
        initComponents();

    }

    public AddBookJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) tableBookTable.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayBook();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLanguages = new javax.swing.JTextField();
        btnBookAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBookPages = new javax.swing.JTextField();
        txtAuthorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGenreName = new javax.swing.JTextField();
        comboBoxRentDuration = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtRentPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        comboBoxAvailable = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboBoxTyoeOfBinding = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Book Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 40));

        txtLanguages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLanguagesFocusLost(evt);
            }
        });
        add(txtLanguages, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 30));

        btnBookAdd.setText("ADD");
        btnBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAddActionPerformed(evt);
            }
        });
        add(btnBookAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 90, -1));

        tableBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK NAME", "No. of Pages", "Languages", "Author", "Genre", "Type of Binding", "Date", "Available", "Rent Price", "Rent Duration", "Serial Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBookTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 780, 250));

        jLabel2.setText("Languages");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 130, 40));

        txtBookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookNameFocusLost(evt);
            }
        });
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });
        add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 30));

        jLabel3.setText("Book Pages");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 40));

        jLabel4.setText("Author");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, 40));

        txtBookPages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookPagesFocusLost(evt);
            }
        });
        txtBookPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookPagesActionPerformed(evt);
            }
        });
        add(txtBookPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        txtAuthorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAuthorNameFocusLost(evt);
            }
        });
        add(txtAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 120, 30));

        jLabel7.setText("Genre");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 40));

        jLabel8.setText("Binding Type");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 40));

        txtGenreName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGenreNameFocusLost(evt);
            }
        });
        txtGenreName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreNameActionPerformed(evt);
            }
        });
        add(txtGenreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 120, 30));

        comboBoxRentDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "one week", "two week", "three week" }));
        add(comboBoxRentDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 120, 30));

        jLabel6.setText("Rental Rate");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 130, 40));

        txtRentPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRentPriceFocusLost(evt);
            }
        });
        add(txtRentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 120, 30));

        jLabel9.setText("Registered Date");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 130, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, 30));

        jLabel10.setText("Can be obtained?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 40));

        comboBoxAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(comboBoxAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 120, 30));

        jLabel11.setText("Rental Period");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 130, 40));

        comboBoxTyoeOfBinding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardcover", "Wire", "Saddle" }));
        add(comboBoxTyoeOfBinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 30));

        jLabel13.setText("Book Serial Number");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 130, 40));

        txtSerialNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSerialNumberFocusLost(evt);
            }
        });
        add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 120, 30));

        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Add Book");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAddActionPerformed
        // TODO add your handling code here:

          String bookName = txtBookName.getText();
          String noOfPages = txtBookPages.getText();
          String languages = txtLanguages.getText();
          String authorName = txtAuthorName.getText();
          String genreName = txtGenreName.getText();
          String typeOfBinding = (String) comboBoxTyoeOfBinding.getSelectedItem();
          Date dateValue = jDateChooser1.getDate();
          String isAvailable =  (String) comboBoxAvailable.getSelectedItem();
          Boolean isAvailableValue;
          if(isAvailable == "Yes")
          {
              isAvailableValue = true;
          }
          else {
              isAvailableValue = false;
          }

          String rentPrice = txtRentPrice.getText();
          String rentDuration = (String) comboBoxRentDuration.getSelectedItem();
          String serialNumber = txtSerialNumber.getText();
          
          
          Library lib = this.branch.getLib();
          Book book = new Book();
          BookDirectory bookcollection = lib.getBooklist();
          
          book.setMaterialName(bookName);
          book.setNoOfPages(Integer.valueOf(noOfPages));
          book.setLanguages(languages);
          book.setAuthorName(authorName);
          book.setGenre(genreName);
          book.setTypeOfBinding(typeOfBinding);
          book.setRegisteredDate(dateValue);
          book.setIsAvailableFlag(isAvailableValue);
          book.setLocation(this.useraccount.getAccessTo());
          Rent rt = book.getRt();
          rt.setRentDuration(rentDuration);
          rt.setRentPrice(Double.valueOf(rentPrice));
          rt.setSerialNumber(Long.valueOf(serialNumber));
          rt.setStatus("Available");
          
          lib.getAuthorCompleteList().addAuthor(authorName);
          lib.getGenreCompleteList().addGenre(genreName);
          
          book.setRt(rt);
          bookcollection.getBooklistCollection().add(book);
          
          lib.setBooklist(bookcollection);

          this.applicationsystem.AddBookToBranch(this.branch.getName(), lib);

          JOptionPane.showMessageDialog(null, "Book Added");

          
          displayBook();
 
          
    }//GEN-LAST:event_btnBookAddActionPerformed

    private void txtLanguagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLanguagesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLanguagesFocusLost

    private void txtBookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameFocusLost

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void txtBookPagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookPagesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookPagesFocusLost

    private void txtAuthorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAuthorNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorNameFocusLost

    private void txtGenreNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGenreNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreNameFocusLost

    private void txtBookPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookPagesActionPerformed

    private void txtRentPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRentPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentPriceFocusLost

    private void txtSerialNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerialNumberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberFocusLost

    private void txtGenreNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAdd;
    private javax.swing.JComboBox<String> comboBoxAvailable;
    private javax.swing.JComboBox<String> comboBoxRentDuration;
    private javax.swing.JComboBox<String> comboBoxTyoeOfBinding;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBookTable;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtBookPages;
    private javax.swing.JTextField txtGenreName;
    private javax.swing.JTextField txtLanguages;
    private javax.swing.JTextField txtRentPrice;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

public String fetchBranchName()
    {
        String BranchName = "";
        String userAccountValue = this.useraccount.getAccountId();      
        ArrayList<Branch> br = this.applicationsystem.getBranches();
        int fetchNumber = 0;
        for(int i=0;i< br.size(); i++){
            String emp = br.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getPersonId();
            if(emp.equals(userAccountValue) ){
                fetchNumber = i;
                break;  
            }
        }
        BranchName = br.get(fetchNumber).getName();
        System.out.println("BRANCH NAME PRINTING "+BranchName);
        return BranchName;
    }

    private void displayBook(){
        viewTableModel.setRowCount(0);
        Library lib = this.branch.getLib();
          ArrayList<Book> bookcollection = lib.getBooklist().getBooklistCollection();

          for(int i =0;i< bookcollection.size();i++ ){
               Object row[] = new Object[11];
               if(bookcollection.get(i).getLocation().equals(useraccount.getAccessTo()))
               {
                     row[0] = bookcollection.get(i).getMaterialName();
                     row[1] = bookcollection.get(i).getNoOfPages();
                     row[2] = bookcollection.get(i).getLanguages();
                     row[3] = bookcollection.get(i).getAuthorName();
                     row[4] = bookcollection.get(i).getGenre();
                     row[5] = bookcollection.get(i).getTypeOfBinding();
                     row[6] = String.valueOf(bookcollection.get(i).getRegisteredDate());
                     row[7] = bookcollection.get(i).getIsAvailableFlag();
                     row[8] = bookcollection.get(i).getRt().getRentPrice();
                     row[9] = bookcollection.get(i).getRt().getRentDuration();
                     row[10] = bookcollection.get(i).getRt().getSerialNumber();
                    
                    viewTableModel.addRow(row);
               }
                  
             
              }    
          }
    }
